# Generated by Django 2.2.7 on 2019-11-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretalx_orcid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcidprofile',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
